spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/algafood?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  liquibase:
    change-log: "db/changelog/db.changelog-master.xml"
# spring.servlet.multipart.max-file-size=8KB

algafood:
  storage:
    tipo-storage: S3
    local:
      diretorio-fotos: /home/jian/Imagens/catalogo/
    s3:
      id-chave-acesso: ${CHAVE_ACESSO}
      chave-acesso-secreta: ${CHAVE_SECRETA}
      bucket: ${BUCKET}
      regiao: ${REGION}
      diretorio-fotos: ${DIR}